//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeChatTransferDemo.NewAccountData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSchemaVersion
    {
        public string ClientVersion { get; set; }
        public long SQLiteSchemaVersion { get; set; }
        public long SchemaUpdateType { get; set; }
    }
}
