//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeChatTransferDemo.OldAccountData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentSharing
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> call_id { get; set; }
        public string identity { get; set; }
        public Nullable<long> status { get; set; }
        public string sharing_id { get; set; }
        public string state { get; set; }
    }
}
