//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeChatTransferDemo.OldAccountData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OldAccountDataEntities : DbContext
    {
        public OldAccountDataEntities()
            : base("name=OldAccountDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<CallHandler> CallHandlers { get; set; }
        public virtual DbSet<CallMember> CallMembers { get; set; }
        public virtual DbSet<Call> Calls { get; set; }
        public virtual DbSet<ChatMember> ChatMembers { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<ContactGroup> ContactGroups { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContentSharing> ContentSharings { get; set; }
        public virtual DbSet<Conversation> Conversations { get; set; }
        public virtual DbSet<ConversationView> ConversationViews { get; set; }
        public virtual DbSet<DataChannel> DataChannels { get; set; }
        public virtual DbSet<DbMeta> DbMetas { get; set; }
        public virtual DbSet<LegacyMessage> LegacyMessages { get; set; }
        public virtual DbSet<MediaDocument> MediaDocuments { get; set; }
        public virtual DbSet<MessageAnnotation> MessageAnnotations { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<SMS> SMSes { get; set; }
        public virtual DbSet<tracker_journal> tracker_journal { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<Translator> Translators { get; set; }
        public virtual DbSet<VideoMessage> VideoMessages { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Voicemail> Voicemails { get; set; }
        public virtual DbSet<AppSchemaVersion> AppSchemaVersions { get; set; }
    }
}
