//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeChatTransferDemo.OldAccountData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracker_journal
    {
        public long id { get; set; }
        public Nullable<long> dbID { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> change { get; set; }
    }
}
