//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeChatTransferDemo.OldAccountData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoMessage
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public byte[] qik_id { get; set; }
        public string attached_msg_ids { get; set; }
        public string sharing_id { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> vod_status { get; set; }
        public string vod_path { get; set; }
        public string local_path { get; set; }
        public string public_link { get; set; }
        public Nullable<long> progress { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string author { get; set; }
        public Nullable<long> creation_timestamp { get; set; }
        public string type { get; set; }
    }
}
